version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
    environment:
      repo_token: HPSkWJD2JPQhrdV7gbuDOPg5pdOVhh6DD
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd NODE_MONGO_TUTORIAL && npm install 
      - run:
          name: Install npm dev dependencies
          command: cd NODE_MONGO_TUTORIAL && npm install mocha nyc chai-http chai
      - run:
          name: Run Unit Tests
          command: cd NODE_MONGO_TUTORIAL && npm run coverage
      - run:
          name: Upload coverage to Coveralls
          command: cd NODE_MONGO_TUTORIAL && npx coveralls < coverage/lcov.info
      - run:
          name: update coverage badge
          command: cd NODE_MONGO_TUTORIAL && npx update-badge
workflows:
  build_tests:
    jobs:
      - run_tests