version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
   
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd NODE_MONGO_TUTORIAL && npm install 
      - run:
          name: Install npm dev dependencies
          command: cd NODE_MONGO_TUTORIAL && npm install mocha nyc chai-http chai
      - run:
          name: Run Unit Tests
          command: cd NODE_MONGO_TUTORIAL && npm test
    
workflows:
  build_tests:
    jobs:
      - run_tests