version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:10.14.2

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm install mocha c8 chai-http chai
      - run: npm run test


